import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "./globals.css";
import { OptionProvider } from "../../providers/option-provider";

const lora = Lora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "focus today!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lora.className}>
        <OptionProvider>{children}</OptionProvider>
      </body>
    </html>
  );
}
